### PR TITLE
Ijm nsm v2

### PR DESCRIPTION
**Pull request by imscw95**
Added carbon, DOX, alkalinity, and CBOD test files. Made edits to the processes.py file where necessary to get the modules to match RAS and the hand calculations.

### CODE REVIEW

**Comment by jrutyna** [comment]
@imscw95, there is one more conflict to resolve. Can you take a look?

**Comment by imscw95** [comment]
Resolved, removed print statement from Kelsey's branch @kewalak that ok?

**Comment by imscw95** [comment]
I am going to update the theta issue before merging this branch, because the changes I made to the hardcoded theta values led to failures in some of the test files. Going to try to solve this before merging.

**Comment by aufdenkampe** [comment]
@imscw95, thanks for keeping this moving forward! Time is getting tight on this deliverable and really appreciate your effort.

**Pull request merged**
